/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sushma' at '7/25/16 8:21 AM' with Gradle 2.14.1
 *
 * @author sushma, @date 7/25/16 8:21 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
